git:
  depth: 5
cache: yarn
matrix:
  include:
    - language: node_js
      node_js:
        - "8"
        - "10"
      script:
        - yarn build
        - yarn lint
        - yarn test-travis

    - language: python
      python: 2.7
      before_script:
        - cd python
        - pip install -r requirements-dev.txt
      script:
        - pylint --rcfile=.pylintrc tensorflowjs
        - ./run-python-tests.sh

    - language: python
      python: 2.7
      before_script:
        - cd python
        - pip install -r requirements-dev.txt
      script:
        - deactivate && ./build-pip-package.sh --test /tmp/tfjs-pips

    - language: python
      python: 3.6
      before_script:
        - cd python
        - pip install -r requirements-dev.txt
      script:
        - pylint --rcfile=.pylintrc tensorflowjs
        - ./run-python-tests.sh
        # Note: Since the build-pip-package.sh script runs both py2 and py3,
        #   there is no need to run it again in this Python 3.6 environment.
